apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: bfh2aiv9e-java-quarkus 
  janus-idp.io/tekton: bfh2aiv9e-java-quarkus
  backstage.io/kubernetes-id: bfh2aiv9e-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bfh2aiv9e-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml